### ISSUE TITLE
Matricies not rendrering correctly

### ISSUE THREAD

**Issue by FredeHoey** [johnbcoughlin/calctex#23]
Great package!
I have an issue with matricies not rendering correctly after being processed by latex, that makes this (rendered by Big language mode):
```
[[1,2,3]
 [4,5,6]
 [7,8,9]]
```
renders like so (by [LaTeX](https://quicklatex.com/cache3/ce/ql_a0c85ee62f853c86f3fdb674695e06ce_l3.png)):
```
(1)23456789
```
The generated LaTeX that I get, when turning off `calctex-mode` looks like this:
```
\begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix}
```
which renders correctly on [quicklatex.com](https://quicklatex.com/cache3/3e/ql_218acd62d81ec77957d1223e165aa53e_l3.png)

Could it be an issue with the parsing?

#### EDIT:
Provided more detail

**Comment by johnbcoughlin** [comment]
Thank you for the issue report! I believe it is fixed by [adding amsmath](https://github.com/johnbcoughlin/calctex/commit/b5714c5382f9064d7bb85490ca798a340c704951) to the latex preamble. Do you mind testing it out now?

**Comment by FredeHoey** [comment]
I've tried to `setq` as well as editing it in `calctex.el`, but unfortunately it doesn't change anything

**Comment by johnbcoughlin** [comment]
Do you mean it doesn't change the value of the variable as shown in `M-x describe-variable`? Or it doesn't change how calctex renders the image? If it's the latter, it may be because calctex is caching the image. I filed #25 to fix that, but for now you can try just changing a digit in the matrix to verify.

To clear the cache, depending on what commit you cloned the repo at, try blowing away either `~/calctex` (old) or the result of `M-: (temporary-file-directory)`

**Comment by FredeHoey** [comment]
You're right. Adding `amsmath` fixed the issue. Great work!
